version: '3'

services:
  backend: 
    build: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports: 
      - "8000:8000"
    #depends_on: 
     # - db
    environment: 
      - PYTHONUNBUFFERED=1

  frontend: 
    build: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
    ports: 
      - "3000:3000"
    stdin_open: true 
    tty: true 

