# Generated by Django 5.1.2 on 2024-11-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
