# Generated by Django 3.2.25 on 2024-12-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_schedule_start_date',
            field=models.DateField(),
        ),
    ]
