# Generated by Django 4.2.17 on 2024-12-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Income'), (1, 'Expense')], default=0)),
                ('schedule_date', models.DateField()),
                ('repeat', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('categories', models.ManyToManyField(related_name='scheduled_transactions', to='logic.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.user')),
            ],
            options={
                'db_table': 'scheduled_transactions',
            },
        ),
    ]
