# Generated by Django 3.2.25 on 2024-12-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20241211_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='hasInterest',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='lender',
        ),
        migrations.AddField(
            model_name='debt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.transaction'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='debt',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
