# Generated by Django 5.1.2 on 2024-11-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_user_curp_user_first_name_user_last_name_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rfc',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
