# Generated by Django 4.2.16 on 2024-11-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_user_curp_user_first_name_user_last_name_father_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('mount', models.FloatField()),
                ('type', models.IntegerField(choices=[(0, 'Income'), (1, 'Expense')], default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
