# Generated by Django 3.2.25 on 2024-12-13 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_user_email_schedule_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='schedule_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_schedule_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
