# Generated by Django 3.2.25 on 2024-12-12 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20241212_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_schedule_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
