# Generated by Django 3.2.25 on 2024-12-12 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_user_email_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='debt',
            name='hasInterest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='debt',
            name='lender',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
