# Generated by Django 4.2.16 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=35, unique=True)),
                ('is_universal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(related_name='transactions', to='logic.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='logic.category'),
        ),
    ]
