# Generated by Django 3.2.25 on 2024-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20241212_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10),
        ),
    ]
