# Generated by Django 3.2.25 on 2024-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20241213_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='schedule_date',
            field=models.DateField(),
        ),
    ]
