# Generated by Django 4.2.16 on 2024-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_category_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_universal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='logic.category'),
        ),
    ]
