# Generated by Django 3.2.25 on 2024-12-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_alter_scheduledtransaction_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='schedule_date',
            field=models.DateTimeField(),
        ),
    ]
