# Generated by Django 4.2.16 on 2024-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_category_is_universal_user_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(related_name='transactions', to='logic.category'),
        ),
    ]
