# Generated by Django 3.2.25 on 2024-12-13 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_alter_scheduledtransaction_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_schedule_start_date',
            field=models.DateField(verbose_name=datetime.date(2024, 12, 13)),
        ),
    ]
