services:
  db:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: BudgetMateDB
      MYSQL_DATABASE: BudgetMate_info
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: django_backend
    command: >
      sh -c "
        ./wait-for-it.sh db:3306 --timeout=30 --
        echo 'DB is ready' && 
        python manage.py makemigrations --merge --noinput && 
        python manage.py migrate --noinput && 
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: react_frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  celery:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ../backend:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    command: celery -A backend beat --loglevel=info
    volumes:
      - ../backend:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:6.0
    container_name: budgetmate-redis
    ports:
      - "6379:6379"

volumes:
  mariadb_data:
